style = "full"
enter_accept = true
search_mode = "daemon-fuzzy"
auto_sync = false
filter_mode = "directory"
workspaces = true
show_numeric_shortcuts = false

[ui]
columns = ["exit", "time", "command"]

[theme]
name = "catppuccin-mocha-blue"

[dotfiles]
enable = false

[daemon]
enabled = true
autostart = true
