[tools]
bun = "latest"
node = "latest"
deno = "2.7.4"
github-cli = "2.87.3"
golang = "1.25.0"
jq = "1.8.1"
"npm:pino-pretty" = "latest"
go = "1.26.1"
fnox = "latest"
usage = "latest"
pnpm = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
kubectl = "latest"
"npm:agent-browser" = "latest"
act = "latest"
"npm:netlify-cli" = "latest"
wrangler = "latest"
claude-code = "latest"
pulumi = "latest"
railway = { version = "latest", exe = "railway" }
"aqua:neovim/neovim" = "latest"
starship = "latest"
atuin = "latest"
bat = "latest"
bombardier = "latest"
caddy = "latest"
chezmoi = "latest"
cloudflared = "latest"
cmake = "latest"
coreutils = "latest"
direnv = "latest"
eza = "latest"
fzf = "latest"
glow = "latest"
gping = "latest"
hyperfine = "latest"
imagemagick = "latest"
jless = "latest"
k9s = "latest"
lazydocker = "latest"
lazygit = "latest"
lazyjournal = "latest"
zoxide = "latest"
opencode = "latest"
xh = "latest"
pipx = "latest"
yazi = "latest"
python = "latest"
ripgrep = "latest"
sqlite = "latest"
infisical = "latest"
age = "latest"

[settings]
color = true

[settings.npm]
package_manager = "bun"

[shell_alias]
m = "mise"

